[project]
name = "ia700-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aksil-Irbouh", email = "aksilirbouh@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "requests>=2.34.2",
    "seaborn>=0.13.2",
]

[project.scripts]
ia700-project = "ia700_project:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]
